require "pulkitgangwar.plugins-setup"
require "pulkitgangwar.core.options"
require "pulkitgangwar.core.colorscheme"
require "pulkitgangwar.core.keymaps"
require "pulkitgangwar.plugins.comment"
require "pulkitgangwar.plugins.nvim-tree"
require "pulkitgangwar.plugins.lualine"
require "pulkitgangwar.plugins.telescope"
require "pulkitgangwar.plugins.bufferline"
require "pulkitgangwar.plugins.nvim-neoclip"
require "pulkitgangwar.plugins.toggleterm"
require "pulkitgangwar.plugins.trouble"
require "pulkitgangwar.plugins.nvim-treesitter"
require "pulkitgangwar.plugins.autopairs"
require "pulkitgangwar.plugins.lsp.nvim-cmp"
require "pulkitgangwar.plugins.lsp.lsp-config"
require "pulkitgangwar.plugins.lsp.mason"
require "pulkitgangwar.plugins.lsp.null-ls"
require "pulkitgangwar.plugins.lsp.lspsaga"



